# Generated by Django 5.2.6 on 2025-11-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_is_active_department_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTimeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_cutoff', models.TimeField(help_text="Time until which students are marked as 'Present' (e.g., 09:30)")),
                ('late_cutoff', models.TimeField(help_text="Time until which students are marked as 'Late'. After this, marked as 'Absent' (e.g., 11:00)")),
            ],
        ),
    ]
