# Generated by Django 5.2.6 on 2025-11-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendancetimesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_cutoff', models.TimeField(default='09:30', help_text='Students arriving before this time will be marked as Present')),
                ('late_cutoff', models.TimeField(default='11:00', help_text='Students arriving between present cutoff and this time will be marked as Late. After this time, they will be marked as Absent.')),
            ],
            options={
                'verbose_name': 'Attendance Time Settings',
                'verbose_name_plural': 'Attendance Time Settings',
            },
        ),
        migrations.DeleteModel(
            name='AttendanceTimeSettings',
        ),
    ]
