# Generated by Django 5.2.6 on 2025-11-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attendancesettings_delete_attendancetimesettings'),
    ]

    operations = [
    ]
