# Generated by Django 5.2.6 on 2025-11-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_leaverequest_reviewed_at_leaverequest_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, help_text='Course code (e.g., MCA, MSCS, BCS)', max_length=20, null=True, unique=True),
        ),
    ]
