# Generated by Django 5.2.6 on 2025-11-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
    ]
