# Generated by Django 5.2.6 on 2025-11-07 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(choices=[('usb', 'USB Camera'), ('ip', 'IP Camera')], default='usb', max_length=10),
        ),
        migrations.AddField(
            model_name='camera',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='camera',
            name='device_index',
            field=models.IntegerField(default=0, help_text='Camera device index for USB cameras (0, 1, 2, etc.)'),
        ),
        migrations.AddField(
            model_name='camera',
            name='fps',
            field=models.IntegerField(default=30, help_text='Frames per second'),
        ),
        migrations.AddField(
            model_name='camera',
            name='ip_address',
            field=models.CharField(blank=True, help_text='Required for IP cameras', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default camera for attendance'),
        ),
        migrations.AddField(
            model_name='camera',
            name='port',
            field=models.IntegerField(blank=True, help_text='Port for IP cameras', null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='resolution_height',
            field=models.IntegerField(default=480, help_text='Video resolution height'),
        ),
        migrations.AddField(
            model_name='camera',
            name='resolution_width',
            field=models.IntegerField(default=640, help_text='Video resolution width'),
        ),
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='camera',
            name='stream_url',
            field=models.URLField(blank=True, help_text='RTSP/HTTP stream URL for IP cameras', null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
